# import turtle
# screen = turtle.Screen()
# screen.title('Turtle code')
# screen.bgcolor('Yellow')
# screen.mainloop()

#####################

# import turtle
# import time
# t = turtle.Turtle()

# t.forward(100)
# time.sleep(5)
# t.forward(50)

# turtle.done()

#####################

import turtle
import time

t = turtle.Turtle()

for x in range(4):

        t.forward(100)
        time.sleep(1)

        t.right(90)
        time.sleep(1)

turtle.done()